server:
  port: "443"
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "quwicly91"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 3
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

  level:
    root: INFO
    lavalink: INFO
